//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        public int AccesoId { get; set; }
        public Nullable<int> RolId { get; set; }
        public Nullable<int> ModuloId { get; set; }
        public Nullable<System.DateTime> CreadoEn { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEn { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
