//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulos()
        {
            this.Accesos = new HashSet<Accesos>();
        }
    
        public int ModuloId { get; set; }
        public string Nombre { get; set; }
        public string TagHTML { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> CreadoEn { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEn { get; set; }
        public Nullable<int> ModificadorPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesos> Accesos { get; set; }
    }
}
