//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros
    {
        public int RegistroId { get; set; }
        public int TareaId { get; set; }
        public int UsuarioId { get; set; }
        public int EtiquetaId { get; set; }
        public int ProyectoId { get; set; }
    
        public virtual Etiquetas Etiquetas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
        public virtual Tareas Tareas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
